export const siteConfig = { name: "Popoyo Performance & Recovery", url: "https://popoyorecovery.com", description: "Personalized bodywork, movement, and performance training for surfers, active travelers, and residents in Popoyo.", whatsappDisplay: "+505 8617 1764", whatsappNumber: "50586171764" };
export const whatsappHref = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent("Hi Popoyo Performance & Recovery, I would like to book a session.")}`;
export const navItems = [{label:"Home",href:"/"},{label:"Services",href:"/#services"},{label:"Approach",href:"/#approach"},{label:"Pricing",href:"/pricing"},{label:"Book",href:"/book"}];
export const services = [
{title:"Surf Recovery & Repair",href:"/surf-recovery-repair",image:"/images/surf-running.jpg",copy:"Recover faster between sessions and get back in the water feeling strong. For paddling fatigue, shoulder tension, low back stiffness, tight hips, and surf-related wear and tear."},
{title:"Sports Massage & Bodywork",href:"/sports-massage-bodywork",image:"/images/sports-massage.jpg",copy:"Targeted hands-on work for tight muscles, chronic tension, and deep release. Designed to improve tissue quality and help your body reset after surfing, training, travel, or daily stress."},
{title:"Performance Training",href:"/performance-training",image:"/images/personal-training.jpg",copy:"Personalized strength, balance, and conditioning built around your goals. One-on-one training for surf performance, general fitness, endurance, balance, and body control."},
{title:"Movement & Mobility",href:"/movement-mobility",image:"/images/stretch-mobility.jpg",copy:"Move with more range, control, and confidence. Focused sessions using assisted stretching, joint mobility, stability work, posture, and body control."},
{title:"Injury Support",href:"/injury-support",image:"/images/coastal-recovery.jpg",copy:"Structured support for minor injuries, pain, and return to activity. Sessions may include movement checks, corrective exercise, mobility work, strengthening, and gradual return-to-activity planning."}
];
export const jsonLd = {"@context":"https://schema.org","@type":"HealthAndBeautyBusiness",name:siteConfig.name,url:siteConfig.url,telephone:siteConfig.whatsappDisplay,priceRange:"Contact for pricing",address:{"@type":"PostalAddress",addressLocality:"Popoyo",addressCountry:"NI"}};
